site_name: Moje projekty
site_author: Marcin Fryś
site_url: https://mardil26.github.io/mf_ai_portfolio/iris/
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!


repo_name: Mardil26/mf_ai_portfolio
repo_url: https://github.com/Mardil26/mf_ai_portfolio


theme:
  name: material
  palette:
    primary: yellow

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "pomocnik Językowy": pomocnik_jezykowy/index.md
- Poprzednie projekty:
  - "Titanic": titanic/index.md
  - "Iris": iris/index.md

markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
